# Generated by Django 4.1.6 on 2023-03-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sn_app', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.TextField(default='caption...'),
        ),
    ]
