# Generated by Django 4.1.2 on 2023-05-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sn_app', '0006_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
